x = 'some long and awesome TEXT'
print(len(x))
print(x[len(x) - 1])
print(x[len(x) - 4:len(x)])
print(x.count('o'))
print(x.find('a'))
print(x.find('o'))
print(x.find('o', 3, 7))
print(x.find('o', 7))
print(x.find('and'))
print(x.find('TEXT'))
print(x.find('abc'))

print()

print(x.capitalize())
print(x.upper())
print(x.lower())
print('Old text: ' + x)
upper_cased = x.upper()
print(upper_cased)
lower_cased = x.lower()
print(lower_cased)
print(upper_cased.isupper())
print(lower_cased.islower())
print(x.isupper())
print(x.islower())
print('xxx777'.isalnum())
print('xxx777!'.isalnum())
print('xxx777!'.isalpha())
print('xxx'.isalpha())

print()

x = str('hello')
print(x.startswith('he'))
print(x.endswith('lo'))
split = x.split('l')
print(type(split))
print(split)
split = x.split('l')
print(x.split('e'))

print()

some_data = '4; 8; 15; 16; 23; 42'
separated_data = some_data.split(';')
print(separated_data)
print(separated_data[3])